### ISSUE TITLE
Moving window analysis for metrics to evaluate non-stationarity

### ISSUE THREAD

**Issue by jds485** [USGS-R/regional-hydrologic-forcings-ml#10]
Mentioned in #6, we should do a moving window analysis for each gauge to see if metrics are changing over time. If there are substantial changes in the metrics' values for some sites, that can help inform if we should limit our analysis to a more recent time period, or use a model structure that can handle non-stationarity. 

Window size can be tested, but I think at least a 20 year window will be needed. 
Increments can be 1 yr to start, but it can be increased if that takes too long to process.

I can see several visuals that could be useful:
1. line plots for each metric for each site over time: y-axis = metric value, x-axis = time.
2. summary line plot for each metric that shows the average value across sites over time. For this to work, I think each site's metric will need to be normalized (metric - mean value over time)/(sd value over time). So we would be plotting the average deviation from average value of each metric.

Feel free to add other ideas

**Comment by jds485** [comment]
We can do formal hypothesis tests of change for non-overlapping portions of the timeseries. Some methods for FDC statistics are in [Kroll et al. (2015)](https://www.sciencedirect.com/science/article/pii/S0022169415007404#:~:text=3.3.%20Test%20sites%20%20%20%20USGS%20number,%20%2009119000%20%2025%20more%20rows%20)

**Comment by jds485** [comment]
@slevin75 Do you want to handle this issue?

**Comment by slevin75** [comment]
Yes, I can do this one.  Probably can't start it until after Christmas.

**Comment by slevin75** [comment]
I may want to chat with you a little before I start this one too to make sure I'm on the same page.
