### ISSUE TITLE
Investigate the COMIDs with multiple streamgages in Gages2.1

### ISSUE THREAD

**Issue by cstillwellusgs** [USGS-R/regional-hydrologic-forcings-ml#104]
Some COMIDs contain multiple streamgages - see Gages2.1_RefSiteList.xlsx, instances when column COMID.DUP == TRUE (gage# in column ID). Should these gages be treated separately or combined as one period of record? Are there overlapping data at the gages or was a gage renumbered and simply moved up/down stream? Potential implications on how these cases are handled for metric calculation.

**Comment by jds485** [comment]
Something on a list to eventually explore is adding an attribute "distance of gage to catchment outlet, as proportion of reach length" to try and account for the error associated with using attributes that are computed for catchment outlets while gages are upstream. That could help for the case you describe above, and potentially for many other gages that are upstream of outlets. I do not have a good sense for how complicated that would be to compute.

**Comment by cstillwellusgs** [comment]
Do you want to create a separate Issue for your above comment?

**Comment by ajsekell** [comment]
The distance from gage to catchment outlet metric would be very cool. Difficult to do I think using stream distance, but maybe easier in terms of straight line distance.
