### ISSUE TITLE
Create train, test, and cross validation splits with nestedness matrix

### ISSUE THREAD

**Issue by jds485** [USGS-R/regional-hydrologic-forcings-ml#112]
PR #110 uses a random split for training and testing, and for cross validation. The `split_data` function should be updated to create splits based on the gage nestedness matrix.

**Comment by slevin75** [comment]
@jds485 
I have implemented the nestedness criteria into the split_data function and the boruta screening functions and now I am trying to work it into the train_models_grid function.  I just want to make sure I know what is going on with the vfold_cv function below. I think this is the function that is splitting the training data for the cross validation.  The output of this function is a list of lists, one for each v_fold.  That inner list has the full training data (item 1), in_id which is a vector of integers (item 2), out_id which is Null, (item 3), and id which is the id of the v_fold (item 4). 

I think that in_id is the selected gages for the cross validation and it corresponds to the line number of the training data? Is that right? So I just need to post process to make sure any gages in a nested group are all within that list? 

If I am not making any sense, you can just call me and we can chat about it.

https://github.com/USGS-R/regional-hydrologic-forcings-ml/blob/78d37bdb744437b5be2f83a74ef67b080144fc58/6_predict/src/train_models.R#L395

**Comment by jds485** [comment]
I have not looked into the details of the lists created by vfold_cv, but that sounds right to me!
