### ISSUE TITLE
additions to screen_daily_data function

### ISSUE THREAD

**Issue by slevin75** [USGS-R/regional-hydrologic-forcings-ml#15]
This is a reminder for myself mostly to add a line in the screen_daily_data function to remove estimated as well as provisional data and also to add the site number to the output table in this function.  Should be a quick fix but I just don't want to forget over the weekend.

**Comment by slevin75** [comment]
Has been fixed and merged.

**Comment by jds485** [comment]
Did you fix this in your copy of the repo?

**Comment by slevin75** [comment]
oh crud - yes, its in my fork but not in this version. What step did I miss? Why is this so confusing to me?!

**Comment by slevin75** [comment]
ok - I forgot to merge it after you reviewed it.  I think it should be updated now.

**Comment by jds485** [comment]
Thanks! I think GitHub will close these issues automatically after the merge when the issue is listed in the PR, so that's why I caught it. I just realized that we didn't add "closes #15" to that PR, so I added that to the comments

**Comment by jds485** [comment]
Actually, it's in the "Linked issues" option on the right panel of the PR
