### ISSUE TITLE
Extend EDA for attributes to CONUS reaches

### ISSUE THREAD

**Issue by jds485** [USGS-R/regional-hydrologic-forcings-ml#151]
Depends on #142.

Create target(s) that create maps and violin plots of the reach attributes across CONUS.
- Would help to have a violin plot with one side for the CONUS distribution and the other side for the training site distribution. That way we can see if any attribute distributions are really different than our training data coverage.
- Not sure how to indicate on a map where we have training sites. Might be too crowded to do.

**Comment by slevin75** [comment]
@jds485   This isn't ready for a pr yet but I have a couple questions.  So far, I have just done comparisons of the gagesii features and the NHD conus features. I haven't looked into the area of applicability yet, I thought it would be good to just look at the raw CONUS data for a sense of how different the distributions are.  I can look into the aoa and try to add those as a 3rd violin plot on these.  These are for the high aggregated quantiles. I'll add another target to do the mid quantiles.  

Right now I just sort of eyeballed the plots and made a list of ones that should be log transformed - things like drainage area. A lot of the plots need to be transformed but have zeros in them.  So - I could either just add a constant and transform just for visualization purposes.  Or the scales packages has a 'pseudo log transform' which I have never used but might be ok for our purposes?  

Here are some examples: 
Definitely a difference in drainage area distributions
![ACC_BASIN_AREA](https://user-images.githubusercontent.com/18313247/227556946-a361f9f8-966b-4ca1-8c85-3487f0a165b3.png)

Should be transformed but has zeros
![TOT_OLSON_PERM](https://user-images.githubusercontent.com/18313247/227557152-27089f6b-b76b-46d6-ab22-a9fae21f0048.png)


![TOT_ELEV_MAX](https://user-images.githubusercontent.com/18313247/227558514-0b59353d-5fa2-4886-a806-c9fcc811e989.png)

**Comment by slevin75** [comment]
Also, the function makes these in a loop and its pretty slow.  It might go faster if it were parallelized but I'm not sure I know how to do that.  I'll try and look at some of the other functions that are parallelized and see if I can figure it out.

**Comment by jds485** [comment]
> I can look into the aoa and try to add those as a 3rd violin plot on these

Just so I'm understanding what would be in that 3rd violin plot: are you thinking that you would apply the aoa method, select the regions within the aoa, and then the 3rd violin plot would be for only those retained reaches? Also, the aoa method would be applied to only the attributes that are used in the models, so some of these attributes would not have a 3rd violin.

> I'll add another target to do the mid quantiles.

Sounds good. Those targets can be added after the high quantile results are working.

> So - I could either just add a constant and transform just for visualization purposes. 

That's fine by me. The idea of pseudo log transform makes sense, though. I've not applied, but for visualization purposes it might be better than adding an arbitrary constant.

> It might go faster if it were parallelized

We can discuss in the meeting later if you can't figure it out.
