### ISSUE TITLE
Edit feature maps for factor attributes

### ISSUE THREAD

**Issue by jds485** [USGS-R/regional-hydrologic-forcings-ml#164]
The EDA feature map for PHYSIO is currently plotting a continuous variable. We should edit to plot as a factor with 1 color per level.

**Comment by slevin75** [comment]
@jds485 Does this look ok for the physio plots?

![image](https://user-images.githubusercontent.com/18313247/208729341-35476a64-bf61-4ab0-af2c-56be9a7a48a1.png)

**Comment by jds485** [comment]
yes, thanks!
