### ISSUE TITLE
take site screening targets out of tar_map

### ISSUE THREAD

**Issue by slevin75** [USGS-R/regional-hydrologic-forcings-ml#20]
take the first few steps out of the tar_map and save a file with the site that pass the screeing criteria to get passed to the tar_map.

### Discussed in https://github.com/USGS-R/regional-hydrologic-forcings-ml/discussions/18

<div type='discussions-op-text'>

<sup>Originally posted by **slevin75** December  3, 2021</sup>
Help me think this through a little.  I set up the repository using static branching which assumes we have a set list of gages and that all those gages will make it through the tar_map block without failing in some way.  As I found out when I ran this for a larger portion of gages, this is problematic because if site has zero complete years, it will fail.   There are some sites, which, even though they are in gagesII don't actually have any daily dishcarge or don't have peak flow in NWIS, so they will fail at different places. I ran into a couple other odd situations as well, which I just manually removed for that period of record analysis.  

So what we need is a data screener that gets the data and then, if there isn't enough data or whatever, that site is dropped and everything else keeps going.  Is there a way to do that within the current set up or should this be reconfigured using dynamic branching? I'm starting to forget how dynamic branching works but I think it was able to accomodate that situation more easily than static branching.</div>

**Comment by slevin75** [comment]
So - this turned out to be kind of a non-trivial thing.   tar_map only accepts a list from a parameter, it doesn't accept other targets, so its hard to use tar_map based on an upstream target.  I can't screen out sites with too few years of complete data unless I download it from NWIS first, so in order to keep it in the static branching format, I'd have to take all the screening functions out of targets.  I don't think we want to do this because then they won't be tracked, so every time we have to run this, its going to re-download and re-screen all daily flows.  

I can do this with dynamic branching though because then each target can iterate through a list of upstream targets.  So, I was able to do all the screening by changing everytying to dynamic branching.  I also tried one another solution where I kept the screening in static branching and then took the subset of sites with enough complete years and sent that to targets where the remainder of the steps use dynamic branching to loop through those sites.  I don't think it adds anything and is really a lot cleaner just doing it all in dynamic branching, but if there is a reason that we might want to keep that static branching in for something else, we could do that.  

Anyway - I have two different branches - the fix_screening_targets branch implements the data screening and calculates the metrics all using dynamic brancing.  fix_screeing_targets_static is where I tried to keep the static branching in place.  I haven't done a PR yet because I just wanted to get your thoughts on it.

**Comment by cstillwellusgs** [comment]
I've only made minor changes. I believe you can fetch upstream to get the latest and greatest. But let's defer to Jared because I'm throwing some pull requests his way as well, not sure what the best sequence will be.

**Comment by jds485** [comment]
Thanks for doing this, Sara! Switching to dynamic branching is fine by me. Can you try to pull in the changes from the USGS-R repo to your new dynamic branch? Hopefully there will not be merge conflicts. I can help you deal with those if they come up. If you want, you can create a new branch from your current dynamic branch to try out pulling from USGS-R

**Comment by slevin75** [comment]
is it git fetch upstream    that would do this? I don't know why the git commands foncuse me so much.  

Some of the changes probably will create some merge conflicts because we don't need a combine function any more for dynamic branching and other functions had to be changed slightly to work as well.

**Comment by jds485** [comment]
`git fetch upstream main` will get the changes from USGS-R and but not merge them. `git pull upstream main` will also merge with your main branch. You will then have to merge your main branch with your dynamic or static branch, which is the step that could have merge conflicts
