### ISSUE TITLE
Style: Change user-defined variables to snake_case

### ISSUE THREAD

**Issue by jds485** [USGS-R/regional-hydrologic-forcings-ml#23]
After the next set of PRs have been merged, let's update our user-defined variable names to be consistent in style with the snake_case convention.

**Comment by jds485** [comment]
Can also change some of the p1 targets to be p2, where p2 is for computing metrics

**Comment by jds485** [comment]
Can also change some of the p1 targets to be p2, where p2 is for computing metrics

**Comment by cstillwellusgs** [comment]
We could renumber p1, p2, etc. at our 'checkpoint' thorough review before modeling begins.

**Comment by jds485** [comment]
Proposed contents of each phase:
p1 – fetching and processing 
p2 – compute metrics 
p3 – unchanged – cluster analysis 
p4 – unchanged – nestedness analysis 
p5 – data exploration + visualization 
p6 - prediction models

**Comment by jds485** [comment]
I started addressing format, and function and parameter descriptions in #125. I did not rename phases.

Something we should consider doing is making a separate R script for each phase. Our _targets.R script is now long.

**Comment by jds485** [comment]
@slevin75 I think this issue can be closed after your renaming PR #130. Is that right?

**Comment by slevin75** [comment]
Yes I'll close it now!
