### ISSUE TITLE
NWIS sites added (and maybe removed?) over time

### ISSUE THREAD

**Issue by jds485** [USGS-R/regional-hydrologic-forcings-ml#24]
Based on issue filed in [drb-inland-salinity repo](https://github.com/USGS-R/drb-inland-salinity-ml/issues/29#issue-1078750511).

> NWIS sites can be added (and maybe also removed?) from one day to the next, which raises reproducibility concerns. We will need a way to handle tracking exactly which sites are pulled to ensure consistency among repo developers and future users.

Proposing to add a git-tracked file with the following columns:
site number
number of samples
summary statistics (mean, sd)

**Comment by jds485** [comment]
In the drb-inland-salinity repo, this issue was addressed by adding log and ind files to track data and targets. We can use a similar approach for our repo. 
Functions: 
1. https://github.com/USGS-R/drb-inland-salinity-ml/blob/main/3_visualize/src/summarize_site_list.R
2. https://github.com/USGS-R/drb-inland-salinity-ml/blob/main/3_visualize/src/summarize_timeseries.R
Targets that call these functions:
1. https://github.com/USGS-R/drb-inland-salinity-ml/blob/main/3_visualize.R

**Comment by jds485** [comment]
@slevin75 @cstillwellusgs Would one of you be able to adapt the functions I've linked for use in our repo? The PR would have a reproducibility and readability theme, so it could also address issue #23

**Comment by slevin75** [comment]
I probably won't have much time in the next week to do anything. We are heading to NH next Tuesday for 2 weeks and I'll be taking an unspecified amount of time off.  I'll probably do some work from out there after Christmas, but I don't know how much yet. I won't assign myself yet in case @cstillwellusgs wants to go for it, but if it is not done when I return, I can take a look at it then.
