### ISSUE TITLE
gage 06408700 causes calcHITmetrics to fail

### ISSUE THREAD

**Issue by slevin75** [USGS-R/regional-hydrologic-forcings-ml#27]
gage 06408700 in SD causes calcHITmetrics fails and I can't figure out why. I don't think its a targets or our pipeline issue, I think its actually an Eflostats issue, so if you run the group of gages near CO, it will fail at that gage.  I haven't found other gages that have this issue yet.

**Comment by jds485** [comment]
I can take a look at this issue associated with the planned work on #25

**Comment by jds485** [comment]
Is this the error message that you were getting? Trying to reproduce the problem and then diagnose why it's happening
> Error: callr subprocess failed: $ operator is invalid for atomic vectors

**Comment by jds485** [comment]
I found the error and it is in the EflowStats code in the `calc_timingHigh` function. In the following if statement, it's possible that all flows are flood flows. When that happens, `nonFloodEvents` = 0 and is not a data.frame as expected. I'll file this as an issue in that repo.
> if (!is.null(floodThreshold)) {
    dailyMaxFlow <- dplyr::summarize(dplyr::group_by(x, 
      day), maxFlow = max(discharge))
    nonFloodEvents <- find_eventDuration(dailyMaxFlow$maxFlow, 
      threshold = floodThreshold, aggType = "none", type = "low", 
      trim = FALSE)
    maxDuration <- max(nonFloodEvents$duration)
    th3 <- maxDuration/365
  }

**Comment by jds485** [comment]
For our project, we will not need these timing metrics or several low flow metrics, so I'm proposing that we specify the `stats` argument in `calc_HITmetrics` as 
stats <- c("calc_magAverage", "calc_magLow", "calc_magHigh", "calc_frequencyHigh", "calc_durationHigh", "calc_rateChange")

**Comment by jds485** [comment]
This error happening makes me very suspicious of the reported flood threshold for this gage. It's impossible to have a full year of flood flows, right?!

**Comment by cstillwellusgs** [comment]
Ha! I'm not a flood expert... but that is suspicious. Another item for us to investigate is the flood threshold itself (if I remember correctly, Sara specifies some parameter = 0.6). Is this flood threshold valid across all regions, drainage area sizes, etc.?

**Comment by slevin75** [comment]
@cstillwellusgs @jds485

That is very odd. I would not expect every value in the time series to be above the 0.6 exceedance probability.  I just ran this gage with EflowStats and it gave me a flood threshold of 6.5 cfs for this gage which is not that far off from what the bulletin 17B estimate for this gage would be (~8-9 cfs from peakFQ). At any rate, there are daily flows below the 6.5 cfs at this gage, but they are all at the begininng and middle of the period of record.  Both the peak flows and daily flows at this gage are wacky and there is an increase in the lower daily flows.  After 2010, all the daily flows probably are greater than the threshold. 

When it is looking for max(nonfloodevents), is it looking at the whole period of record or just a subset of the record?  If it is going through something like a moving window or its looking by year to see how many daily flows per year are above that threshold per year,  in that case I could see how it could come up with this problem at this gage becuase all these flows at the end of the record are relatively high. 


@cstillwellusgs  the 0.6 exceedance probability  is ~1.5 yr return period (would actually be the 0.66 exceedence probability) which is often used as a rule of thumb value for the bank-full flood discharge.  Some of the duration metrics I think use this - like the duration or frequency that the stream exceeds this assumed bankful. I know in MN they use this value for some sediment modeling they do in our wsc. Anyway - it is totally not a valid assumption everywhere and is probably very site specific but it is used fairly widely, for better or for worse, lol.

**Comment by jds485** [comment]
When I was debugging, it was a single year of flows that were all greater than the flood threshold. So I think it's computing the value on an annual basis

**Comment by cstillwellusgs** [comment]
Thanks for the explanation @slevin75. I'd like to discuss this more at our next meeting. I agree that 'bankfull' is a good starting point, but I wonder if we should explore different flood thresholds as well.

**Comment by jds485** [comment]
With the FDC-based metrics, we'll have thresholds for all quantiles we select. I'm currently computing frequency, magnitude, duration, and volume metrics for quantiles ranging from 50 - 99%

**Comment by cstillwellusgs** [comment]
Right - I guess that is why I'm confused about this 0.6 (or 1.5-yr) threshold. That seems limited to the analysis of peaks, but I wonder what the implications of different thresholds would be on that analysis.

**Comment by jds485** [comment]
The EflowStats repo has been updated to fix the error when the whole year has flood flows, so this gage should work now without error. Looking more closely at the code for the th3 metric, it is finding the proportion of the calendar year that experiences flood flows. So it takes the maximum flow for each day, regardless of the year. That is why it's possible to have the full year experience flood flows
