### ISSUE TITLE
Check the spatial nestedness of gages to inform spatial cross validation groups

### ISSUE THREAD

**Issue by jds485** [USGS-R/regional-hydrologic-forcings-ml#36]
Goal is to develop groups of nested gages to inform spatial cross validations. The analysis can be applied to all gages in our reference GAGES-based dataset. We can subset the results to the gages we select for modeling.

**Comment by slevin75** [comment]
So - I have started looking at the streamline_trace.R code and after putting together a matrix which identifies which gages are upstream of each other (1 if it is upstream, 0 if not), it reads a file called "example_compiled_data/PK100Statistic_v2.csv" and updates any "1" values in the matrix based on whether or not the gage  is included in this file and whether or not the gage in the file has non-null 'variance' data.  Do you know what this file is or if we can get it or recreate it?

**Comment by slevin75** [comment]
Ok that should be pretty simple then. I guess at some later point, when we set up the validation groups, we might need to find some cutoff point at which we are not considering the nesting to be redundant  like a tiny headwater gage and a huge mainstem gage downstream.  Even though they are nested, the processes that control flow and timing are likely quite different at those two spatial scales.

**Comment by jds485** [comment]
Yes, I agree. I think Ken suggested this as a research question to test how model performance changes as we change the nestedness tolerance
