### ISSUE TITLE
Create long-term monthly average weather features

### ISSUE THREAD

**Issue by jds485** [USGS-R/regional-hydrologic-forcings-ml#62]
As discovered in the [drb-inland-salinity-ml repo](https://github.com/USGS-R/drb-inland-salinity-ml/issues/80), the precipitation and temperature data are provided monthly, and need to be processed to obtain the 50-year average of the monthly values. We should be able to use code from that repo to create those long-term monthly average values for our modeling needs.

See [calc_monthly_avg_ppt](https://github.com/USGS-R/drb-inland-salinity-ml/blob/main/2_process/src/process_nhdv2_attr.R) function. Note that this function has hard-coded use of the years 1971-most recent, but we can use all 50 available years for this repo.

**Comment by cstillwellusgs** [comment]
There are also annual precipitation and temperature norms (1971 - 2000) available, in case we don't want to invest time to the processing of monthly values. But I think it wouldn't be a huge deal to use the monthly, especially once we are on the HPC.

Attributes for NHDPlus Version 2.1 Catchments and Modified Routing of Upstream Watersheds for the Conterminous United States: 30 Year (1971 - 2000) Mean Annual Precipitation - ScienceBase-Catalog<https://www.sciencebase.gov/catalog/item/573b70a7e4b0dae0d5e3ae85?community=National+Water-Quality+Assessment+-+Hydrologic+Systems+Team+%28NAWQA+-+HST%29>

Attributes for NHDPlus Version 2.1 Catchments and Modified Routing of Upstream Watersheds for the Conterminous United States: 30 Year (1971 - 2000) Mean Annual Temperature (Celsius) - ScienceBase-Catalog<https://www.sciencebase.gov/catalog/item/57054bf2e4b0d4e2b756d364?community=National+Water-Quality+Assessment+-+Hydrologic+Systems+Team+%28NAWQA+-+HST%29>

From: Jared D Smith ***@***.***>
Sent: Tuesday, March 1, 2022 2:03 PM
To: USGS-R/regional-hydrologic-forcings-ml ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [USGS-R/regional-hydrologic-forcings-ml] Create long-term monthly average weather features (Issue #62)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



As discovered in the drb-inland-salinity-ml repo<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUSGS-R%2Fdrb-inland-salinity-ml%2Fissues%2F80&data=04%7C01%7Ccstillwell%40usgs.gov%7C0753c56fd3c54eea4d0608d9fbb6e2dc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637817585181666583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=f%2FOIbN8vCYJ%2BfEBG6F%2Bl7tWeO%2FR%2B9Vje3djd4LKFVAw%3D&reserved=0>, the precipitation and temperature data are provided monthly, and need to be processed to obtain the 50-year average of the monthly values. We should be able to use code from that repo to create those long-term monthly average values for our modeling needs.

See calc_monthly_avg_ppt<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUSGS-R%2Fdrb-inland-salinity-ml%2Fblob%2Fmain%2F2_process%2Fsrc%2Fprocess_nhdv2_attr.R&data=04%7C01%7Ccstillwell%40usgs.gov%7C0753c56fd3c54eea4d0608d9fbb6e2dc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637817585181666583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vFuuh68K8RFE%2Byq8Pm5r4ZHepVwe7Jl%2FoO9IB%2FhnPlo%3D&reserved=0> function. Note that this function has hard-coded use of the years 1971-most recent, but we can use all 50 available years for this repo.

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUSGS-R%2Fregional-hydrologic-forcings-ml%2Fissues%2F62&data=04%7C01%7Ccstillwell%40usgs.gov%7C0753c56fd3c54eea4d0608d9fbb6e2dc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637817585181666583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Rf9uGa56nYMBZqLY%2Fh0Z%2BAQ%2FyFzJu2YeQq%2FK%2BcVHgyM%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKNBENCZVQNMBBORC4TOTETU5ZSUZANCNFSM5PU4ORQA&data=04%7C01%7Ccstillwell%40usgs.gov%7C0753c56fd3c54eea4d0608d9fbb6e2dc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637817585181666583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SKzL62b%2F09w4ftn1MiSpdzkDrHV4wo%2Fo1Xd8gyYNMj4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccstillwell%40usgs.gov%7C0753c56fd3c54eea4d0608d9fbb6e2dc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637817585181666583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ddY5q61prh5OfSpKUWaVm%2BHDdFVHzgQGUSNzKPyRG6Y%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccstillwell%40usgs.gov%7C0753c56fd3c54eea4d0608d9fbb6e2dc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637817585181666583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xvpRgCPTCDtoldUW4QXgNA9UFV2GnY0qD2LSUSjoQko%3D&reserved=0>.

**Comment by jds485** [comment]
We have those annual variables downloaded. I'm thinking that the monthly variables will help because we do see differences in the seasonal distributions of flood responses across the clusters

**Comment by cstillwellusgs** [comment]
Do you want to retain the weather data by individual month/year then append `p1_sb_data_g2_csv` with the new columns, or create a separate .csv and target with the individual month/year weather data dropped?

**Comment by jds485** [comment]
I think it can be a separate csv with the individual month/year dropped

**Comment by cstillwellusgs** [comment]
Since there will be a few separate functions for manipulating the master variable table, I'm thinking to save the output from each with column 1 as COMID with all other columns only related to that function (in this case weather, in other cases land use and dam data). Then, a final target to re-merge the manipulated data back with the other variables.
