### ISSUE TITLE
Screening funtion to get list of potential gages from gagesII (or gagesIII?)

### ISSUE THREAD

**Issue by slevin75** [USGS-R/regional-hydrologic-forcings-ml#7]
https://github.com/slevin75/regional-hydrologic-forcings-ml/blob/269e8247a983b9295246edcefecdef10385a37da/_targets.R#L26-L28

We will need to get a screening function to get the list of reference gages within our region from gagesIII and save it to target p1_sites_list.  For now, I have just manually put in a list of sites.

**Comment by jds485** [comment]
The GAUGES2.1 data are now available in our SharePoint Data folder as Gages2.1_RefSiteList.xlsx. Because this is a small file, I'm thinking we can load it into R, save as an rds file, and commit that rds file to the repo in 1_fetch/in to be used with the pipeline
