### ISSUE TITLE
Modify screen_daily_data to handle sites without any approved data

### ISSUE THREAD

**Issue by cstillwellusgs** [USGS-R/regional-hydrologic-forcings-ml#71]
Site "01011500" (and potentially other sites) contain only NA or provisional data - this causes an error in the screen_daily_data function.

**Comment by jds485** [comment]
Does that site's daily values look like this for you? I'm wondering if the data on NWIS is now different than when I last fetched it.
![image](https://user-images.githubusercontent.com/8761242/157884070-ba1a62e6-9c80-4c45-bd92-a138fc4dbfb4.png)

**Comment by cstillwellusgs** [comment]
All "A"s have changed to "P"s - just verified manually and is confirmed in my daily flow log output for that site (no approved data).

**Comment by jds485** [comment]
Weird! Thanks for checking. In any case, it will be good to have a check that the dataframes have at least 1 row.
