### ISSUE TITLE
add dynamic branching for SB downloads

### ISSUE THREAD

**Issue by jds485** [USGS-R/regional-hydrologic-forcings-ml#78]
For target `p1_make_sb_landscapedata` (function `download_children`) that downloads SB items, it would help to use branching over the SB IDs in the event that the download stops midway.

**Comment by jds485** [comment]
@cstillwellusgs, this is related to #75. I think you could map over `p1_sb_table_reduced`, but some function edits to `download_children` would be needed

**Comment by cstillwellusgs** [comment]
Is dynamic branching (mapping) equivalent to parallel processing? I thought we weren't supposed to go parallel when downloading data.

**Comment by jds485** [comment]
No, dynamic branching will make a separate branch for each of the rows in the SB table, which are the download links. (ref)[https://books.ropensci.org/targets/dynamic.html#branching-over-rows]. We can still process each of the branches in serial with deployment = main

**Comment by cstillwellusgs** [comment]
Ah, I see! Well, I'd like to merge the other branch first then address this separately since I'm less familiar with dynamic branching. Don't want to go too far down the rabbit hole and get lost haha. I'll start on this issue once you've approved #75 and I've merged it to main.
