### ISSUE TITLE
Investigate oddities in sb variable data frame

### ISSUE THREAD

**Issue by cstillwellusgs** [USGS-R/regional-hydrologic-forcings-ml#80]
Ten COMIDs are repeated in the output from 'p1_sb_data_g2_csv'. There is a column titled COMID.DUP (logical) and all duplicated columns are 'TRUE'. Why are these duplicated, and should they be removed?

Additionally, two columns have non-descriptive names.

- 940: originally '...1.x' and renamed to '...940' when read in using 'read_csv()'
- 956: originally '...1.y' and renamed to '...956' when read in using 'read_csv()'

**Comment by cstillwellusgs** [comment]
- Rows 940 and 956 are within the Basin Characteristics datase (https://www.sciencebase.gov/catalog/item/57976a0ce4b021cadec97890)

**Comment by cstillwellusgs** [comment]
- Looks like the duplicated COMIDs are reaches with multiple gages in the Gages2.1 dataset. Quick inspection (not comprehensive) suggests that all variable values are equivalent... so would it be okay to merge duplicated rows?

**Comment by jds485** [comment]
> would it be okay to merge or drop duplicated rows

Yes, that sounds good to me. We should look at where these gages are located and see if we should merge them into one timeseries (e.g., maybe the gage was moved over time, or maybe they are close enough to each other to merge). Do you think checking into that is in scope of this issue, or do you see that as a separate issue?

**Comment by cstillwellusgs** [comment]
I think that is relevant for this issue. I was planning to table it until Monday because Andrew might know more.

**Comment by cstillwellusgs** [comment]
Issues for me/Jared:
•	Why are some COMIDs duplicated, and can they be merged/dropped?
o	COMID.DUP is a column in Gages 2.1 – represents gages on same COMID reach
o	For explanatory variables, likely select whichever is furthest downstream (but think critically about time-varying attributes)
o	For metric calculation, look into period of record, investigate overlaps, etc. (was gage moved? Another added? Up/down from a dam? Etc.)
•	Three columns from the ROAD_DENS_...._CONUS (basin attributes - 57976a0ce4b021cadec97890) have no column header and values are row numbers
o	Can be omitted from explanatory values table
o	Col AIN = ID.y (header assigned by R)
o	Col AJD = …1.x to …940 (header assigned by R)
o	Col AJT = …1.y to …952 (header assigned by R)
•	Not all NLCD data included in current explanatory variables table
o	5d66b3b6e4b0c4f70cefb11d included in FULL table, was removed from REDUCED table

Issues for Andrew/Mike:
•	‘Percent NLCD 2011 in 50 Meter Riparian Buffer’ appears twice!
o	570577fee4b0d4e2b7571d7b is actually impervious 2011 in 100m buffer
o	57855ddee4b0e02680bf37bf is correct, and includes different land classes
•	CAT_IMPV01 is both catchment impervious in 01 (land cover) and catchment improved in 01 (BMPs)
o	Also for ACC and TOT
o	R renames as CAT_IMPV01.x and CAT_IMPV01.y, be careful when selecting which to grab

**Comment by cstillwellusgs** [comment]
(Jared - not expecting a response now, recording for future reference. I'll chat you in Teams to figure out how you'd like to proceed.)
