### ISSUE TITLE
Create long-term average BMP datasets

### ISSUE THREAD

**Issue by cstillwellusgs** [USGS-R/regional-hydrologic-forcings-ml#83]
ACC_IMPV00 (... 12)
CAT
TOT

BEWARE OF CAT_IMPV01 (duplicated from impervious - impervious renamed CAT_IMPV01.x, BMPs renamed CAT_IMPV01.y)

**Comment by cstillwellusgs** [comment]
@jds485 since the BMP data only span 2000 - 2012 do we want to omit from further analyses?

**Comment by jds485** [comment]
I actually did not have BMPs as a priority attribute to use, so I am fine with omitting them

**Comment by cstillwellusgs** [comment]
BMPs already were omitted based on latest version in main branch; closing this issue.
