### ISSUE TITLE
04153500 crashes pipeline at screen_daily_data

### ISSUE THREAD

**Issue by slevin75** [USGS-R/regional-hydrologic-forcings-ml#85]
@jds485 and @cstillwellusgs when I reran the pipeline to make that nonstationary figure for the presentation the other day, site 04153500 crashed the pipeline after the prescreening step.  This is because the screen_daily_data function is mapping over has_data but this site gets removed in the prescreen_daily_data step, so when it tries to map over that has_data target, there's nothing there.  I think we had talked about this before and I'm not sure if it was on anyone's to-do list to fix it? If not - I can add an issue and fix it pretty quick.

_Originally posted by @slevin75 in https://github.com/USGS-R/regional-hydrologic-forcings-ml/discussions/84_

**Comment by cstillwellusgs** [comment]
This site sounds familiar. If you don't mind holding off a bit I can try to remember.

**Comment by slevin75** [comment]
ok, I'll hold off for now.
