### ISSUE TITLE
Weighted averages for time-varying predictor variables

### ISSUE THREAD

**Issue by cstillwellusgs** [USGS-R/regional-hydrologic-forcings-ml#98]
- [x] Land Use (awaiting guidance from Terry Sohl, Mike Wieczorek)
- [x] Dams
- [x] Weather??

**Comment by jds485** [comment]
We can apply the weighted average to weather data, too, and compare to using the simple average over all available years

**Comment by cstillwellusgs** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/CSTILL~1/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/CSTILL~1/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Dataset | Start Year | End Year | Year Type | Timestep | In-bounds | Out-of-bounds
-- | -- | -- | -- | -- | -- | --
Flows | 1901 | 2020 | Water | Daily | na | na
Precip | 1945 | 2015 | Calendar | Monthly | convert to WY | ?
Temp | 1945 | 2015 | Calendar | Monthly | convert to WY | ?
LULC (Sohl) | 1940 | 2100 | Calendar | Decadal | round to nearest decade | assume 1940 for all pre-1940?
Dams | 1930 | 2010 | Calendar | Decadal | round to nearest decade | assume 1930 for all pre-1930?
Wildfire | 2000 | 2012 | Calendar | Annual | long-term average | long-term average



</body>

</html>

**Comment by jds485** [comment]
Probably use long-term average for precip and temp out of bounds. That's what we currently use, right? So the weighted adjustment will be a little better than that if we have data precip and temp data in-bounds, and otherwise will reflect a long-term 1945-2015 average.

I think it's safe to assume land cover and dams did not change much before 1940. I made the same assumption for PUMP project work.

**Comment by cstillwellusgs** [comment]
@jds485 @slevin75 @ajsekell 

Alternative 1) Only utilize flows from 1945 onward?
Alternative 2) Scrap this idea of weighted averages and just stick with the long-term averages?
Alternative 3) Mix and match of long-term averages and weighted averages based on variable?

**Comment by cstillwellusgs** [comment]
So the final answer is...

- Precip and Temp - weighted average when applicable, long-term avg where not applicable
- LULC and Dams - assume dates too early same as earliest available

**Comment by cstillwellusgs** [comment]
Need to combine the modeled LULC from these two datasets:

- https://www.sciencebase.gov/catalog/item/58cbeef2e4b0849ce97dcd61?community=National+Water-Quality+Assessment+-+Hydrologic+Systems+Team+%28NAWQA+-+HST%29
- https://www.sciencebase.gov/catalog/item/5b96c2f9e4b0702d0e826f6d

**Comment by jds485** [comment]
@cstillwellusgs is this issue good to close?

**Comment by cstillwellusgs** [comment]
nope - was planning to get to it this week... then ran out of time.

**Comment by jds485** [comment]
I think that's still worth it. We'll probably miss more changes after 2000 than before 1940, but that's okay. And our catchments being minimally altered may not have seen much change from 2000 - 2020

**Comment by cstillwellusgs** [comment]
If our catchments are minimally altered... no LULC should change too much right?

**Comment by jds485** [comment]
Yes. Could have differences in undeveloped classes, though (grass to forest).
